version: '3.8'

services:
  mysql-employee-directory:
    image: mysql
    restart: always
    env_file:
      - ./server/.env
    volumes:
      - mysql-employee-directory:/var/lib/mysql
  server:
    build: ./server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    environment:
      NODE_ENV: docker
    depends_on:
      - mysql-employee-directory
    command: ["sh", "./server/entrypoint.sh"]
  client:
    build: ./client
    ports:
      - "5173:80"
    depends_on:
      - server
    restart: unless-stopped
    
volumes:
  mysql-employee-directory: {}